# Generated by Django 3.0.5 on 2022-05-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploaded_files')),
                ('table_name', models.CharField(default='table', max_length=100)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
